### ISSUE TITLE
Instructions how to set up Xdebug + PHPStorm (and others) for D8 development

### ISSUE THREAD

**Issue by kallevu** [druidfi/guidelines#3]
According to [D8 documentation](https://www.drupal.org/docs/8/theming/twig/debugging-twig-templates) one should use Xdebug for developing the theme. 

> Far and beyond the best way to deal with printing out variables is to use xdebug. 

We should add documentation how to set up IDE for xdebug and make sure infra repos have unified configuration for xdebug.

**Comment by back-2-95** [comment]
Fixed with #4
